CREATE (a:dgl{name:"_ffi",def:dir,address:"dgl"}),(a1:_ffi{name:"_ctypes",def:dir,address:"dgl/_ffi"}),(a1a:_ctypes {name:"__init__.py",def:file,address:"dgl/_ffi/_ctypes"}),(a1b:_ctypes {name:"function.py",def:file,address:"dgl/_ffi/_ctypes"}),(a1c:_ctypes {name:"ndarray.py",def:file,address:"dgl/_ffi/_ctypes"}),(a1d:_ctypes {name:"object.py",def:file,address:"dgl/_ffi/_ctypes"}),(a1e:_ctypes {name:"types.py",def:file,address:"dgl/_ffi/_ctypes"}),(a2:_ffi {name:"_cy2",def:dir,address:"dgl/_ffi"}),(a2a:_cy2 {name:"__init__.py",def:file,address:"dgl/_ffi/_cy2"}),(a3:_ffi {name:"_cy3",def:dir,address:"dgl/_ffi"}),(a3a:_cy3 {name:"__init__.py",def:file,address:"dgl/_ffi/_cy3"}),(a4:_ffi {name:"__init__.py",def:file,address:"dgl/_ffi"}),(a5:_ffi {name:"base.py",def:file,address:"dgl/_ffi"}),
(a6:_ffi {name:"function.py",def:file,address:"dgl/_ffi"}),
(a7:_ffi {name:"libinfo.py",def:file,address:"dgl/_ffi"}),
(a8:_ffi {name:"ndarray.py",def:file,address:"dgl/_ffi"}),
(a9:_ffi {name:"object.py",def:file,address:"dgl/_ffi"}),
(a10:_ffi {name:"object_geometric.py",def:file,address:"dgl/_ffi"}),
(a11:_ffi {name:"runtime_ctypes.py",def:file,address:"dgl/_ffi"}),
(b:dgl {name:"backend",def:dir,address:"dgl"}),
(b1:backend {name:"mxnet",def:diraddress:"dgl/backend"}),
(b1a:mxnet {name:"__init__.py",def:file,address:"dgl/backend/mxnet"}),
(b1b:mxnet {name:"tensor.py",def:file,address:"dgl/backend/mxnet"}),
(b2:backend {name:"numpy",def:dir,address:"dgl/backend"}),
(b2a:numpy {name:"__init__.py",def:file,address:"dgl/backend/numpy"}),
(b2b:numpy {name:"tensor.py",def:file,address:"dgl/backend/numpy"}),
(b3:backend {name:"pytorch",def:dir,address:"dgl/backend"}),
(b3a:pytorch {name:"__init__.py",def:file,address:"dgl/backend/pytorch"}),
(b3b:pytorch {name:"tensor.py",def:file,address:"dgl/backend/pytorch"}),
(b4:backend {name:"__init__.py",def:file,address:"dgl/backend"}),
(b5:backend {name:"backend.py",def:file,address:"dgl/backend"}),


  (c:dgl {name:"contrib",address:"dgl"}),
(c1:contrib {name:"data.py",def:dir,address:"dgl/contrib"}),
(c1a:data {name:"__init__.py",def:file,address:"dgl/contrib/data"}),
(c1b:data {name:"knowledge_graph.py",def:file:"dgl/contrib/data"}),
(c2:contrib {name:"sampling",def:dir,address:"dgl/contrib"}),
(c2a:sampling {name:"__init__.py",def:file,address:"dgl/contrib/sampling"}),
(c2b:sampling {name:"dis_sampling.py",def:file,address:"dgl/contrib/sampling"}),
(c2c:sampling {name:"randomwalk.py",def:file,address:"dgl/contrib/sampling"}),
(c2d:sampling {name:"sampler.py",def:file,address:"dgl/contrib/sampling"}),
(c3:contrib {name:"__init__.py",def:file,address:"dgl/contrib"}),
(c4:contrib {name:"graph_store.py",def:file,address:"dgl/contrib"}),


  (d:dgl {name:"data",address:"dgl/data"}),
(d1:data {name:"__init__.py",def:file,address:"dgl/data"}),
(d2:data {name:"citation_graph.py",def:file,address:"dgl/data"}),
(d3:data {name:"gindit.py",def:file,address:"dgl/data"}),
(d4:data {name:"minigc.py",def:file,address:"dgl/data"}),
(d5:data {name:"ppi.py",def:file,address:"dgl/data"}),
(d6:data {name:"reddit.py",def:file,address:"dgl/data"}),
(d7:data {name:"sbm.py",def:file,address:"dgl/data"}),
(d8:data {name:"tree.py",def:file,address:"dgl/data"}),
(d9:data {name:"tu.py",def:file,address:"dgl/data"}),
(d10:data {name:"utils.py",def:file,address:"dgl/data"}),

  (e:dgl {name:"function",def:dir,address:"dgl/function"}),
(e1:function {name:"__init__.py",def:file,address:"dgl/function"}),
(e2:function {name:"base.py",def:file,address:"dgl/function"}),
(e3:function {name:"message.py",def:file,address:"dgl/function"}),
(e4:function {name:"reducer.py",def:file,address:"dgl/function"}),


  (f:dgl {name:"nn",def:dir,address:"dgl"}),
(f1:nn {name:"mxnet.py",def:dir,address:"dgl/nn"}),
(f1a:mxnet {name:"__init__.py",def:file,address:"dgl/nn/mxnet"}),
(f1b:mxnet {name:"conv.py",def:file,address:"dgl/nn/mxnet"}),
(f1c:mxnet {name:"softmax.py",def:file,address:"dgl/nn/mxnet"}),
(f2:nn {name:"pytorch.py",def:dir,address:"dgl/nn"}),
(f2a:pytorch {name:"__init__.py",def:file,address:"dgl/nn/pytorch"}),
(f2b:pytorch {name:"conv.py",def:file,address:"dgl/nn/pytorch"}),
(f2c:pytorch {name:"softmax.py",def:file,address:"dgl/nn/ptorch"}),
(f3:nn {name:"__init__.py",def:file,address:"dgl/nn"}),

(g:dgl {name:"runtime",def:dir,address:"dgl"}),
(g1:runtime {name:"ir",def:dir,address:"dgl/runtime"}),
(g1a:ir {name:"__init__.py",def:file,address:"dgl/runtime/ir"}),
(g1b:ir {name:"executor.py",def:file,address:"dgl/runtime/ir"}),
(g1c:ir {name:"program.py",def:file,address:"dgl/runtime/ir"}),
(g1d:ir {name:"registry.py",def:file,address:"dgl/runtime/ir"}),
(g1e:ir {name:"var.py",def:file,address:"dgl/runtime/ir"}),
(g2:runtime {name:"__init__.py",def:file,address:"dgl/runtime"}),
(g3:runtime {name:"degree_bucketing.py",def:file,address:"dgl/runtime"}),
(g4:runtime {name:"runtime.py",def:file,address:"dgl/runtime"}),
(g5:runtime {name:"scheduler.py",def:file,address:"dgl/runtime"}),
(g6:runtime {name:"spmv.py",def:file,address:"dgl/runtime"}),

  (h:dgl {name:"__init__.py",def:file,address:"dgl"}),
  (i:dgl {name:"_api_internal.py",def:file,address:"dgl"}),
  (j:dgl {name:"base.py",def:file,address:"dgl"}),
  (k:dgl {name:"batched_graph.py",def:file,address:"dgl"}),
  (l:dgl {name:"container.py",def:file,address:"dgl"}),
  (m:dgl {name:"frame.py",def:file,address:"dgl"}),
  (n:dgl {name:"graph.py",def:file,address:"dgl"}),
  (o:dgl {name:"graph_index.py",def:file,address:"dgl"}),
  (p:dgl {name:"heterograph.py",def:file,address:"dgl"}),
  (q:dgl {name:"init.py",def:file,address:"dgl"}),
  (r:dgl {name:"kernel.py",def:file,address:"dgl"}),
  (s:dgl {name:"ndarray.py",def:file,address:"dgl"}),
  (t:dgl {name:"network.py",def:file,address:"dgl"}),
  (u:dgl {name:"nodeflow.py",def:file,address:"dgl"}),
  (v:dgl {name:"propagate.py",def:file,address:"dgl"}),
  (w:dgl {name:"random.py",def:file,address:"dgl"}),
  (x:dgl {name:"subgraph.py",def:file,address:"dgl"}),
  (y:dgl {name:"transform.py",def:file,address:"dgl"}),
  (z:dgl {name:"traversal.py",def:file,address:"dgl"}),
  (zz:dgl {name:"udf.py",def:file,address:"dgl"}),
  (zzz:dgl {name:"utils.py",def:file,address:"dgl"}),
  (zzzz:dgl {name:"view.py",def:file,address:"dgl"}),

  (a)-[:CONTAIN]->(a1),
  (a)-[:CONTAIN]->(a2),
  (a)-[:CONTAIN]->(a3),
  (a)-[:CONTAIN]->(a4),
  (a)-[:CONTAIN]->(a5),
  (a)-[:CONTAIN]->(a6),
  (a)-[:CONTAIN]->(a7),
  (a)-[:CONTAIN]->(a8),
  (a)-[:CONTAIN]->(a9),
  (a)-[:CONTAIN]->(a10),
  (a)-[:CONTAIN]->(a11),
  (a1)-[:CONTAIN]->(a1a),
  (a1)-[:CONTAIN]->(a1b),
  (a1)-[:CONTAIN]->(a1c),
  (a1)-[:CONTAIN]->(a1d),
  (a1)-[:CONTAIN]->(a1e),
  (a2)-[:CONTAIN]->(a2a),
  (a3)-[:CONTAIN]->(a3a),
  (b)-[:CONTAIN]->(b1),
  (b)-[:CONTAIN]->(b2),
  (b)-[:CONTAIN]->(b3),
  (b)-[:CONTAIN]->(b4),
  (b)-[:CONTAIN]->(b5),
  (b1)-[:CONTAIN]->(b1a),
  (b1)-[:CONTAIN]->(b1b),
  (b2)-[:CONTAIN]->(b2a),
  (b2)-[:CONTAIN]->(b2b),
  (b3)-[:CONTAIN]->(b3a),
  (b3)-[:CONTAIN]->(b3b),
  (c)-[:CONTAIN]->(a),
(c)-[:CONTAIN]->(c1),
(c)-[:CONTAIN]->(c2),
(c)-[:CONTAIN]->(c3),
(c)-[:CONTAIN]->(c4),
(c1)-[:CONTAIN]->(c1a),
(c1)-[:CONTAIN]->(c1b),
(c2)-[:CONTAIN]->(c2a),
(c2)-[:CONTAIN]->(c2b),
(c2)-[:CONTAIN]->(c2c),
(c2)-[:CONTAIN]->(c2d),
(d)-[:CONTAIN]->(d1),
(d)-[:CONTAIN]->(d2),
(d)-[:CONTAIN]->(d3),
(d)-[:CONTAIN]->(d4),
(d)-[:CONTAIN]->(d5),
(d)-[:CONTAIN]->(d6),
(d)-[:CONTAIN]->(d7),
(d)-[:CONTAIN]->(d8),
(d)-[:CONTAIN]->(d9),
(d)-[:CONTAIN]->(d10),
 (e)-[:CONTAIN]->(e1),
 (e)-[:CONTAIN]->(e2),
 (e)-[:CONTAIN]->(e3),
  (e)-[:CONTAIN]->(e4),
  (f)-[:CONTAIN]->(f1),
  (f)-[:CONTAIN]->(f2),
  (f)-[:CONTAIN]->(f3),
  (f1)-[:CONTAIN]->(f1a),
  (f1)-[:CONTAIN]->(f1b),
  (f1)-[:CONTAIN]->(f1c),
(f2)-[:CONTAIN]->(f2a),
(f2)-[:CONTAIN]->(f2b),
(f2)-[:CONTAIN]->(f2c),

  (e)-[:CONTAIN]->(e1),
  (e)-[:CONTAIN]->(e2),
  (e)-[:CONTAIN]->(e3),
  (e)-[:CONTAIN]->(e4),
  (e)-[:CONTAIN]->(e5),
  (e)-[:CONTAIN]->(e6),
(e1)-[:CONTAIN]->(e1a),
(e1)-[:CONTAIN]->(e1b),
(e1)-[:CONTAIN]->(e1c),
(e1)-[:CONTAIN]->(e1d),
(e1)-[:CONTAIN]->(e1e),


(h)-[:CALL]->(e),
(h)-[:CALL]->(f),
(h)-[:CALL]->(c),
(h)-[:CALL]->(l),
(h)-[:CALL]->(w),
(h)-[:CALL]->(a11),
(h)-[:CALL]->(a6),
(h)-[:CALL]->(a5),
(h)-[:CALL]->(j),
(h)-[:CALL]->(b),
(h)-[:CALL]->(k),
(h)-[:CALL]->(n),
(h)-[:CALL]->(u),
(h)-[:CALL]->(z),
(h)-[:CALL]->(y),
(h)-[:CALL]->(v),
(h)-[:CALL]->(zz),
(j)-[:CALL]->(a5),
(j)-[:CALL]->(a6),
(k)-[:CALL]->(b2),
(k)-[:CALL]->(j),
(k)-[:CALL]->(m),
(k)-[:CALL]->(n),
(k)-[:CALL]->(o),
(k)-[:CALL]->(b),
(k)-[:CALL]->(d10),
(l)-[:CALL]->(a9),
(l)-[:CALL]->i),
(m)-[:CALL]->(b),
(m)-[:CALL]->(b2),
(m)-[:CALL]->(j),
(m)-[:CALL]->(q),
(m)-[:CALL]->(zzz),
(n)-[:CALL]->(a),
(n)-[:CALL]->(j),
(n)-[:CALL]->(b),
(n)-[:CALL]->(q),
(n)-[:CALL]->(m),
(n)-[:CALL]->(o),
(n)-[:CALL]->(g),
(n)-[:CALL]->(zzz),
(n)-[:CALL]->(zz),
(n)-[:CALL]->(zzzz),
(o)-[:CALL]->(b2),


(o)-[:CALL]->(a9),
(o)-[:CALL]->(a6),
(o)-[:CALL]->(j),
(o)-[:CALL]->(b),
(o)-[:CALL]->(zzz),
(q)-[:CALL]->(b),
(r)-[:CALL]->(a6),
(r)-[:CALL]->(a8),
(a8)-[:CALL]->(a1),
(s)-[:CALL]->(b2),
(s)-[:CALL]->(s),
(s)-[:CALL]->(b),
(t)-[:CALL]->(a6),
(t)-[:CALL]->(u),
(t)-[:CALL]->(zzz),
(u)-[:CALL]->(a9),
(u)-[:CALL]->(a6),
(u)-[:CALL]->(j),
(u)-[:CALL]->(b),
(u)-[:CALL]->(m),
(u)-[:CALL]->(n),
(u)-[:CALL]->(o),
(u)-[:CALL]->(g),
(u)-[:CALL]->(zzz),
(u)-[:CALL]->(zzzz),
(v)-[:CALL]->(z),
(w)-[:CALL]->(a6),
(x)-[:CALL]->(m),
(x)-[:CALL]->(n),
(x)-[:CALL]->(zzz),
(x)-[:CALL]->(j),
(x)-[:CALL]->(o),
(y)-[:CALL]->(a6),
(y)-[:CALL]->(k),
(y)-[:CALL]->(n),
(z)-[:CALL]->(a6),
(z)-[:CALL]->(b),
(z)-[:CALL]->(zzz),
(zz)-[:CALL]->(j),
(zz)-[:CALL]->(b),
(zz)-[:CALL]->(zzz),
(zzz)-[:CALL]->(b2),
(zzz)-[:CALL]->(j),
(zzz)-[:CALL]->(b),
(zzz)-[:CALL]->(s),
(zzzz)-[:CALL]->(j),
(zzzz)-[:CALL]->(b),
(a5)-[:CALL]->(b2),
(a6)-[:CALL]->(a5),
(a8)-[:CALL]->(b2),
(a8)-[:CALL]->(a11),
(a9)-[:CALL]->(a10),
(a9)-[:CALL]->(a5),
(a10)-[:CALL]->(a5),
(a11)-[:CALL]->(b2),
(a11)-[:CALL]->(a5),
(a1b)-[:CALL]->(a5),
(a1b)-[:CALL]->(a10),
(a1b)-[:CALL]->(a11),
(a1b)-[:CALL]->(a1c),
(a1b)-[:CALL]->(a1e),
(a1b)-[:CALL]->(a1d),
(a1c)-[:CALL]->(a5),
(a1c)-[:CALL]->(a11),
(a1c)-[:CALL]->(a1e),
(a1d)-[:CALL]->(a5),
(a1d)-[:CALL]->(a10),
(a1d)-[:CALL]->(a1e),
(a1d)-[:CALL]->(a1),
(a1e)-[:CALL]->(a1),
(a1e)-[:CALL]->(a5),
(a1e)-[:CALL]->(a11),
(b4)-[:CALL]->(b5),
(b1b)-[:CALL]->(b2),
(b1b)-[:CALL]->(b1),
(b1b)-[:CALL]->(s),
(b1b)-[:CALL]->(r),
(b1a)-[:CALL]->(b1b),
(b2a)-[:CALL]->(b2b),
(b2b)-[:CALL]->(b2),
(b3a)-[:CALL]->(b3b),
(b3b)-[:CALL]->(r),
(b3b)-[:CALL]->(s),
(c3)-[:CALL]->(c2),
(c3)-[:CALL]->(c4),
(c4)-[:CALL]->(b2),
(c4)-[:CALL]->(j),
(c4)-[:CALL]->(b),
(c4)-[:CALL]->(n),
(c4)-[:CALL]->(zzz),
(c4)-[:CALL]->(o),
(c4)-[:CALL]->(a6),
(c4)-[:CALL]->(a8),
(c4)-[:CALL]->(s),
(c4)-[:CALL]->(q),
(c1a)-[:CALL]->(c1b),
(c1b)-[:CALL]->(b2),
(c1b)-[:CALL]->(d10),
(c2a)-[:CALL]->(c2b),
(c2a)-[:CALL]->(c2c),
(c2a)-[:CALL]->(c2d),
(c2b)-[:CALL]->(t),
(c2c)-[:CALL]->(b),
(c2c)-[:CALL]->(zzz),
(c2c)-[:CALL]->(a6),
(c2d)-[:CALL]->(a6),
(c2d)-[:CALL]->(zzz),
(c2d)-[:CALL]->(b),
(c2d)-[:CALL]->(u),
(d1)-[:CALL]->(d2),
(d1)-[:CALL]->(d4),
(d1)-[:CALL]->(d8),
(d1)-[:CALL]->(d10),
(d1)-[:CALL]->(d7),
(d1)-[:CALL]->(d6),
(d1)-[:CALL]->(d5),
(d1)-[:CALL]->(d9),
(d1)-[:CALL]->(d3),
(d2)-[:CALL]->(b2),
(d2)-[:CALL]->(t),
(d2)-[:CALL]->(zzz),
(d2)-[:CALL]->(a),
(d3)-[:CALL]->(b2),
(d3)-[:CALL]->(d10),
(d3)-[:CALL]->(n),
(d4)-[:CALL]->(t),
(d4)-[:CALL]->(b2),
(d4)-[:CALL]->(n),
(d5)-[:CALL]->(b2),
(d5)-[:CALL]->(t),
(d5)-[:CALL]->(d10),
(d5)-[:CALL]->(n),
(d6)-[:CALL]->(b2),
(d6)-[:CALL]->(a),
(d6)-[:CALL]->(d10),
(d7)-[:CALL]->(w),
(d7)-[:CALL]->(b2),
(d7)-[:CALL]->(t),
(d7)-[:CALL]->(k),
(d7)-[:CALL]->(n),
(d7)-[:CALL]->(zzz),
(d8)-[:CALL]->(b2),
(d8)-[:CALL]->(a),
(d8)-[:CALL]->(b),
(d8)-[:CALL]->(d10),
(d9)-[:CALL]->(b2),
(d9)-[:CALL]->(a),
(d9)-[:CALL]->(w),
(d9)-[:CALL]->(d10),
(e1)-[:CALL]->(e3),
(e1)-[:CALL]->(e4),
(e1)-[:CALL]->(e2),
(e3)-[:CALL]->(e2),
(e3)-[:CALL]->(g),
(e3)-[:CALL]->(g1),
(e4)-[:CALL]->(e2),
(e4)-[:CALL]->(g),
(e4)-[:CALL]->(g1),
(f1a)-[:CALL]->(f2b),
(f1a)-[:CALL]->(f2c),
(f1b)-[:CALL]->(f1),
(f1b)-[:CALL]->(e),
(f1c)-[:CALL]->(f1),
(f1c)-[:CALL]->(e),
(f2a)-[:CALL]->(f2b),
(f2a)-[:CALL]->(f2c),
(f2b)-[:CALL]->(e),
(f2c)-[:CALL]->(e),
(g2)-[:CALL]->(g5),
(g2)-[:CALL]->(g4),
(g3)-[:CALL]->(a6),
(g3)-[:CALL]->(b),
(g3)-[:CALL]->(zz),
(g3)-[:CALL]->(zzz),
(g3)-[:CALL]->(g1),
(g5)-[:CALL]->(zzz),
(g5)-[:CALL]->(a6),
(g5)-[:CALL]->(j),
(g5)-[:CALL]->(b),
(g5)-[:CALL]->(m),
(g5)-[:CALL]->(e2),
(g5)-[:CALL]->(zz),
(g5)-[:CALL]->(g1),
(g5)-[:CALL]->(g1e),
(g5)-[:CALL]->(g3),(g5)-[:CALL]->(g6),(g5)-[:CALL]->(s),(g6)-[:CALL]->(j),(g6)-[:CALL]->(b),(g6)-[:CALL]->(zzz),(g6)-[:CALL]->(s),(g6)-[:CALL]->(o),(g6)-[:CALL]->(g1),(g6)-[:CALL]->(g1e),(g1a)-[:CALL]->(g1b),(g1a)-[:CALL]->(g1c),(g1b)-[:CALL]->(b),(g1b)-[:CALL]->(m),(g1b)-[:CALL]->(zzz),(g1b)-[:CALL]->(g1c),(g1b)-[:CALL]->(g1e),(g1b)-[:CALL]->(g1d),(g1c)-[:CALL]->(g1d),(g1e)-[:CALL]->(g1c),RETURN a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,zz,zzz,zzzz,a1,a2,a3,a1a,a1b,a1c,a1d,a1e,a2a,a3a,a4,a5,a6,a7,a8,a9,a10,a11,b1,b1a,b1b,b2,b2a,b2b,b3,b3a,b3b,b4,b5,c1,c1a,c1b,c2,c2a,c2b,c2c,c2d,c3,c4,d1,d2,d3,d4,d5,d6,d7,d8,d9,d10,e1,e2,e3,e4,f1,f1a,f1b,f1c,f2,f2a,f2b,f2c,f3,g1,g1a,g1b,g1c,g1d,g1e,g2,g3,g4,g5,g6
